#!/bin/bash
#
# This file is providing some APIs for string conversions.

##
# Convert the passed input string to lower string.
#
# Arguments:
#   $1 - Input string to convert to lower string.
# Returns:
#   lower_string - Converted lower string.
#
function to_lower() {
  echo $1 | tr '[:upper:]' '[:lower:]'
}

##
# Convert the passed input string to upper string.
#
# Arguments:
#   $1 - Input string to convert to upper string.
# Returns:
#   upper_string - Converted upper string.
#
function to_upper() {
  echo $1 | tr '[:lower:]' '[:upper:]'
}
